### ISSUE TITLE
Create new documentation

### ISSUE THREAD

**Issue by yayuyokitano** [yayuyokitano/lastfm-typed#12]
This is a big one, will require a separate site pretty much

**Comment by tomnieuwland** [comment]
Very excited to see the outcome of this.

**Comment by yayuyokitano** [comment]
> Very excited to see the outcome of this.

Adding on that the site is in the works and the code is on yayuyokitano/lastfm-typed-docs
Havent been able to do as much work on it as I would've liked to recently, but it is starting to approach completion.
Hope to have it completed by the start of my next semester in early October.
Have basically used it as a massive excuse to learn react+routing lmao
