### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by metehus** [yayuyokitano/lastfm-typed#15]
I've tried to use this library with gatsby on browser and gave me that problem:
![image](https://user-images.githubusercontent.com/22124518/136732191-52a9df7f-4286-45d7-bd2e-68cd868edbe2.png)

**Comment by metehus** [comment]
nvm, I've just used a polyfill

**Comment by yayuyokitano** [comment]
Glad you solved it! Just adding onto this, I have been considering making a browser oriented version that does not require polyfills to save on bundle size, as it is currently a bit larger than I'd like it to be thanks to the needed polyfills.
