### ISSUE TITLE
getRecentTracks response is missing date

### ISSUE THREAD

**Issue by salzmanndavid** [yayuyokitano/lastfm-typed#9]
The response of getRecentTracks does not include the scrobble's date field.

**Comment by yayuyokitano** [comment]
Ah oops. Should have this fixed by the end of the day. I noticed you are on a repo using a pre-1.0.0 version and there were some breaking changes with 1.0.0, so I'll make sure to setup a bugfix-only deprecated branch for pre-1.0.0 as well for convenience.

**Comment by yayuyokitano** [comment]
This should now be fixed with 1.0.2.
Additionally, I have side-published 0.5.2 to the v0 branch of this repo with this fix, without 1.0.0 content.
Thanks for reporting!
